drop table if exists
users,
categories,
events;

CREATE TABLE IF NOT EXISTS users (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email    VARCHAR(254) NOT NULL UNIQUE,
    name     VARCHAR(250) NOT NULL
);

CREATE TABLE IF NOT EXISTS categories (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cat_name    VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS events (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    initiator           BIGINT NOT NULL REFERENCES users(id)        ON DELETE CASCADE,
    categories_id       BIGINT NOT NULL REFERENCES categories(id)   ON DELETE RESTRICT,
    title               VARCHAR(120) NOT NULL,
    annotation          VARCHAR(2000) NOT NULL,
    description         VARCHAR(7000) NOT NULL,
    state               VARCHAR(20) NOT NULL,
    lat                 FLOAT,
    lon                 FLOAT,
    participant_limit   BIGINT NOT NULL,
    request_moderation  BOOLEAN NOT NULL,
    paid                BOOLEAN NOT NULL,
    event_date          TIMESTAMP NOT NULL,
    published_on        TIMESTAMP,
    created_on          TIMESTAMP NOT NULL
);